using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ToDoReminder
{
    public partial class MainForm : Form
    {
        private TaskManager taskManager;

        /// <summary>
        /// Working with only one file located in the same directory as the 
        /// application
        /// </summary>
        private string fileName = Application.StartupPath + "\\Tasks.txt";
        /// <summary>
        /// Dafault constructor generated by VS
        /// </summary>
        public MainForm()
        {
            //VS initialized method
            InitializeComponent();

            InitializeGUI();
        }
        /// <summary>
        /// All  the initailization is done here, the method can be 
        /// recalled to reset the program
        /// </summary>
        private void InitializeGUI()
        {
            this.Text = "ToDo Reminder by Harrison Katantazi";

            taskManager = new TaskManager();

            cmbPriority.Items.Clear();
            cmbPriority.Items.AddRange(Enum.GetNames(typeof(PriorityType)));
            cmbPriority.SelectedIndex = (int)PriorityType.Normal;

            listBox1.Items.Clear();
           //lblClock.Text = string.Empty;
           //clockTimer.Start();

            txttodo.Text = String.Empty;

            dateTimePicker1.Format = DateTimePickerFormat.Custom;
            dateTimePicker1.CustomFormat = "yyyy-MM-dd    HH:mm";

            toolTip1.ShowAlways = true;

            toolTip1.SetToolTip(dateTimePicker1, "click to open calendar for date, write in the time here ");
            toolTip1.SetToolTip(cmbPriority, "Select the priority");

            //string txtOut = string.Format("You Have {0} tasks.", lstReservations.Items.Count);
            string tips = "TO CHANGE: Select an item first!" + Environment.NewLine;
            tips += "Make your changes in the input controls!" + Environment.NewLine;
            tips = tips + "Click the Change button." + Environment.NewLine;

            toolTip1.SetToolTip(listBox1, tips);
            toolTip1.SetToolTip(btnchange, tips);

            string delTips = "Select an Item first and then click this button!";
            toolTip1.SetToolTip(btndelete, delTips);

            string desTips = "Write your schedule here!";
            toolTip1.SetToolTip(txttodo, desTips);

            openDataFileToolStripMenuItem.Enabled = true;
            saveDataFileToolStripMenuItem.Enabled=true;

            
        }
        private Task ReadInput()
        {
            Task task = new Task();

            if (string.IsNullOrEmpty(txttodo.Text))
            {
                MessageBox.Show("No subject? write something please,", "Hello.....");
                return null;
            }
            task.Priority = (PriorityType)cmbPriority.SelectedIndex;
            task.TaskDate = dateTimePicker1.Value;
            task.Description = txttodo.Text;

            return task;
        }

        private void btnadd_Click(object sender, EventArgs e)
        {
           Task task = ReadInput();
            if (taskManager.AddNewTask(task))
            {
                UpdateGUI();
            }
            else
                MessageBox.Show("press to add this to the list");

        }

        private void openDataFileToolStripMenuItem_Click(object sender, EventArgs e)
        {
            string errMessage = "Something Went Wrong when opening the file";
            bool ok = taskManager.ReadDataFromFile(fileName);
            if (!ok)
                MessageBox.Show(errMessage);
            else
                UpdateGUI();
        }

        private void exitAltF4ToolStripMenuItem_Click(object sender, EventArgs e)
        {
            DialogResult dlgResult = MessageBox.Show("Are you sure you want to exit the program?", "Think twice", MessageBoxButtons.OKCancel);
            if (dlgResult == DialogResult.OK)
                Application.Exit();
        }

       
        private void UpdateGUI()
        {
            listBox1.Items.Clear();
            string[] infoStrings = taskManager.GetInfoString();
            if (infoStrings != null)
                listBox1.Items.AddRange(infoStrings);
            
        }

        private void saveDataFileToolStripMenuItem_Click(object sender, EventArgs e)
        {
            string errMeassage = "Something went wrong while saving data to file";
            bool ok = taskManager.WriteDataToFile(fileName);
            if (ok)
                MessageBox.Show("Data saved to file:" + Environment.NewLine + fileName);
            else
                MessageBox.Show(errMeassage);
        }

        private void lblClocktimerr_Click(object sender, EventArgs e)
        {
            lblClocktimerr.Text = DateTime.Now.ToLongTimeString();
        }

        private void btnchange_Click(object sender, EventArgs e)
        {
            int index = listBox1.SelectedIndex;
            if (index >= 0)
            {
                Task task = ReadInput();
                bool ok = taskManager.ChangeTaskAt(task, index);
                if (ok)
                    UpdateGUI();
            }
            else
                MessageBox.Show("Select an element to change!");
        }

        private void btndelete_Click(object sender, EventArgs e)
        {
            int index = listBox1.SelectedIndex;
            if (index >= 0)
            {
                Task task = ReadInput();
                bool ok = taskManager.DeleteTaskAt(index);
                if (ok)
                    UpdateGUI();
            }
            else
                MessageBox.Show("Please select the item to delete");
        }
    }
}
